fix: allow operator to update finalizers
Prior to this change - the following errors were encountered:

```
SEVERE: An additional input failed after the first. Logging it after adding the first failure as a suppressed exception.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.217.4.1/api/v1/namespaces/hivemq/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services "hivemq-hivemq-cluster" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>.
```

```
SEVERE: An additional input failed after the first. Logging it after adding the first failure as a suppressed exception.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.217.4.1/api/v1/namespaces/hivemq/services. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. services "hivemq-hivemq-mqtt" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>.

```